# Datos de energía que publica publish_power_data()

float32 voltage
float32 current
float32 temperature
float32 charge
float32 capacity

bool   home_base
bool   internal_charger

uint8  ir_char_omni
uint8  ir_char_left
uint8  ir_char_right

bool   left_wheel_overcurrent
bool   right_wheel_overcurrent
bool   main_brush_overcurrent
bool   side_brush_overcurrent

int32  left_motor_current
int32  right_motor_current
int32  main_brush_motor_current
int32  side_brush_motor_current
